coach.name=Freedom Lukhele
team.name=the only porkchops

# configuring the springboot embedded server port
server.port=7070


#
#Set the context path of the application
#
#All requests should be prefixed with /coolapp
#
server.servlet.context-path=/coolApp

